# Generated by Django 4.0.1 on 2022-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_themeavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedgameby',
            name='users',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
